[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    { id = "detect-private-key", priority = 0 },
    { id = "check-added-large-files", priority = 0 },
    { id = "trailing-whitespace", priority = 0 },
    { id = "end-of-file-fixer", priority = 0 },
]

[[repos]]
repo = "https://github.com/Yelp/detect-secrets"
rev = "v1.5.0"
hooks = [{ id = "detect-secrets", priority = 0 }]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "chezmoi-validate"
name = "Dry-run chezmoi apply to catch template errors early"
entry = "chezmoi apply --dry-run --force --no-tty"
language = "system"
priority = 0
pass_filenames = false

# [[repos.hooks]]
# id = "chezmoi-apply"
# name = "Run chezmoi apply for non-script files"
# entry = '''bash -c 'chezmoi managed --include=files,dirs -0 | rg -vz -- "\.plist$" | sed -z "s|^|$HOME/|" | xargs -0 chezmoi apply --include=files,dirs --no-tty' '''
# language = "system"
# files = '^(?!.*\.sh$).*$'
# pass_filenames = false
