#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#	Fullchee Zhang
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source $HOME/.aliases
source $HOME/.functions
source $HOME/.private_aliases
export PATH=/bin:/usr/bin:/usr/local/bin:~/.npm-global/bin:$PATH
. ~/z.sh