#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#	Fullchee Zhang
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source $HOME/.aliases
source $HOME/.functions
source $HOME/.private_aliases
source /etc/environment
export PATH=/bin:/usr/bin:/usr/local/bin
export PATH=~/.npm-global/bin:$PATH
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
. ~/z.sh

# added by Anaconda3 installer
export PATH="/home/fullchee/anaconda3/bin:$PATH"
source /home/fullchee/anaconda3/etc/profile.d/conda.sh
