services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /home/fullchee/jellyfin/config:/config          # config files & metadata
      - /home/fullchee/jellyfin/cache:/cache            # temp/cache storage
      - type: bind
        source: /mnt/media/movies
        target: /media
      - type: bind
        source: /mnt/media/tv
        target: /media2
        read_only: true
    restart: 'unless-stopped'
